### ISSUE TITLE
Русские слова в lang/en/pagination.php

### ISSUE THREAD

**Issue by zFriks** [moad-dev/course.feedback#108]
https://github.com/moad-dev/course.feedback/blob/28a7f3616bf6aed2caab0c4b694dae5ff9c9b61c/lang/en/pagination.php#L16

**Comment by bulatovv** [comment]
Первый стороний issue!

1. В приложении не настроена мультиязычность (и ближайшей перспективе не планируется)
2. Авторитарно настроена русская локаль для всех пользователей
3. Lang строчки используются только в тех местах, где они уже были во фреймворке. Свои мы не настраивали (во всем интерфейсе просто русский текст без локализации)

Правки, конечно, мизерные, но и приоритет у них по указанным выше причинам маленький. Поправить можно разве что для консистентности. Если сам оформишь пулл-реквест - будет классно
